# Generated by Django 2.0.4 on 2018-04-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('user_pass', models.CharField(max_length=264)),
                ('user_first_name', models.CharField(max_length=20)),
                ('user_last_name', models.CharField(max_length=30)),
                ('user_contact', models.IntegerField()),
                ('user_email', models.EmailField(max_length=50)),
                ('user_city', models.CharField(max_length=50)),
                ('user_state', models.CharField(max_length=30)),
            ],
        ),
    ]
