# Generated by Django 2.0.4 on 2018-04-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='static/upload/'),
        ),
    ]
