# Generated by Django 2.0.4 on 2018-04-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180417_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='upload/no-img.jpg', upload_to='upload/'),
        ),
    ]
