# Generated by Django 2.0.4 on 2018-04-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180418_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(blank=True, default='profile_image/default.png', upload_to='profile_images'),
        ),
    ]
